dist: xenial
sudo: false
language: python
cache: pip

script:
  - tox

install:
  - pip install tox

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36

    - python: "3.7"
      env: TOXENV=py37

    - python: "3.8"
      env: TOXENV=py38

    # Linting
    - python: "3.8"
      env: TOXENV=lint

notifications:
  email: false
  irc: "irc.freenode.org#xelnext"
